services:
  mysql:
    image: mysql:8.0
    container_name: database-main-production
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: database-main-production
      MYSQL_USER: app_user
      MYSQL_PASSWORD: userpass
    ports:
      - "3314:3306"               # mapea el puerto 3306 del contenedor al 3314 de tu host
    volumes:
      - mysql-data-production:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    image: sena/app-backend:latest
    container_name: app-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
    depends_on:
      mysql:
        condition: service_healthy


volumes:
  mysql-data-production: